version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: scarf
      POSTGRES_USER: scarf
      POSTGRES_PASSWORD: scarf
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://scarf:scarf@db:5432/scarf
      DATABASE_SSL: disable
      OPENAI_API_KEY: change-me
      JWT_SECRET: change-me-please-keep-32-characters
    ports:
      - '3000:3000'

volumes:
  postgres_data:
