CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS restaurants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  google_place_id TEXT UNIQUE,
  latitude NUMERIC(10,7) NOT NULL,
  longitude NUMERIC(10,7) NOT NULL,
  address TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  price_level INTEGER,
  google_rating NUMERIC(2,1),
  google_review_count INTEGER,
  cuisine_tags TEXT[],
  phone TEXT,
  website TEXT,
  photo_urls TEXT[],
  hours JSONB,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  last_scraped_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS restaurant_features (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE UNIQUE,
  romantic NUMERIC(3,2),
  cozy NUMERIC(3,2),
  casual NUMERIC(3,2),
  noise_level NUMERIC(3,2),
  energy_level NUMERIC(3,2),
  crowdedness NUMERIC(3,2),
  good_for_dates NUMERIC(3,2),
  good_for_groups NUMERIC(3,2),
  family_friendly NUMERIC(3,2),
  business_appropriate NUMERIC(3,2),
  celebration_worthy NUMERIC(3,2),
  fast_service NUMERIC(3,2),
  attentive_service NUMERIC(3,2),
  authentic NUMERIC(3,2),
  creative_menu NUMERIC(3,2),
  comfort_food NUMERIC(3,2),
  healthy_options NUMERIC(3,2),
  portions_large NUMERIC(3,2),
  vegan_friendly NUMERIC(3,2),
  photogenic_food NUMERIC(3,2),
  decor_quality NUMERIC(3,2),
  photo_friendly_lighting NUMERIC(3,2),
  nice_views NUMERIC(3,2),
  trendy NUMERIC(3,2),
  outdoor_seating NUMERIC(3,2),
  easy_parking NUMERIC(3,2),
  reservations_needed NUMERIC(3,2),
  late_night NUMERIC(3,2),
  formality NUMERIC(3,2),
  good_value NUMERIC(3,2),
  splurge_worthy NUMERIC(3,2),
  popularity NUMERIC(3,2),
  confidence_score NUMERIC(3,2),
  review_count_analyzed INTEGER,
  last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  model_version TEXT
);
