export const FEATURE_NAMES = [
  'romantic',
  'cozy',
  'casual',
  'noise_level',
  'energy_level',
  'crowdedness',
  'good_for_dates',
  'good_for_groups',
  'family_friendly',
  'business_appropriate',
  'celebration_worthy',
  'fast_service',
  'attentive_service',
  'authentic',
  'creative_menu',
  'comfort_food',
  'healthy_options',
  'portions_large',
  'vegan_friendly',
  'photogenic_food',
  'decor_quality',
  'photo_friendly_lighting',
  'nice_views',
  'trendy',
  'outdoor_seating',
  'easy_parking',
  'reservations_needed',
  'late_night',
  'formality',
  'good_value',
  'splurge_worthy',
  'popularity',
] as const;

export type FeatureName = (typeof FEATURE_NAMES)[number];

export const FEATURE_COLUMN_MAP: Record<FeatureName, string> = {
  romantic: 'romantic',
  cozy: 'cozy',
  casual: 'casual',
  noise_level: 'noiseLevel',
  energy_level: 'energyLevel',
  crowdedness: 'crowdedness',
  good_for_dates: 'goodForDates',
  good_for_groups: 'goodForGroups',
  family_friendly: 'familyFriendly',
  business_appropriate: 'businessAppropriate',
  celebration_worthy: 'celebrationWorthy',
  fast_service: 'fastService',
  attentive_service: 'attentiveService',
  authentic: 'authentic',
  creative_menu: 'creativeMenu',
  comfort_food: 'comfortFood',
  healthy_options: 'healthyOptions',
  portions_large: 'portionsLarge',
  vegan_friendly: 'veganFriendly',
  photogenic_food: 'photogenicFood',
  decor_quality: 'decorQuality',
  photo_friendly_lighting: 'photoFriendlyLighting',
  nice_views: 'niceViews',
  trendy: 'trendy',
  outdoor_seating: 'outdoorSeating',
  easy_parking: 'easyParking',
  reservations_needed: 'reservationsNeeded',
  late_night: 'lateNight',
  formality: 'formality',
  good_value: 'goodValue',
  splurge_worthy: 'splurgeWorthy',
  popularity: 'popularity',
};

export const PROMPT_VERSION = 'feature-extraction-v1';

export const FEATURE_DESCRIPTIONS: Record<FeatureName, string[]> = {
  romantic: [
    'Dim lighting, candlelight, or soft ambiance',
    'Intimate seating meant for couples',
    'Special-occasion or date-night energy',
  ],
  cozy: [
    'Warm, inviting, or homey atmosphere',
    'Comfortable seating or intimate layout',
    'Guests feel relaxed and settled in',
  ],
  casual: [
    'Relaxed dress code or informal vibe',
    'Counter service or simple table settings',
    'Suitable for drop-in or everyday meals',
  ],
  noise_level: [
    'Overall loudness of space',
    'Mentions of quiet, noisy, or hard to talk',
    'Crowd roar, music volume, or kitchen noise',
  ],
  energy_level: [
    'High-energy, vibrant feel vs calm setting',
    'Mentions of lively music or buzzing crowd',
    'General excitement or subdued atmosphere',
  ],
  crowdedness: [
    'How packed or busy the space feels',
    'Mentions of long waits or tight seating',
    'Standing room, cramped aisles, or elbow room',
  ],
  good_for_dates: [
    'Explicitly called out as great for dates',
    'Romantic setups or privacy for couples',
    'Special touches that impress a partner',
  ],
  good_for_groups: [
    'Large tables or easy group seating',
    'Family-style dishes or shareable plates',
    'Handles celebrations or big parties well',
  ],
  family_friendly: [
    'Welcomes children or families',
    'Kids menu, high-chairs, or stroller friendly',
    'Staff tolerant of noise or kid behavior',
  ],
  business_appropriate: [
    'Quiet enough for conversation or meetings',
    'Professional service or polished environment',
    'Mentions of client lunches or business dinners',
  ],
  celebration_worthy: [
    'Birthday, anniversary, or celebration hotspot',
    'Staff acknowledges milestones or brings extras',
    'Festive atmosphere that feels special',
  ],
  fast_service: [
    'Food arrives quickly after ordering',
    'Mentions of swift staff or short waits',
    'Good for quick lunches or tight schedules',
  ],
  attentive_service: [
    'Servers check in often and anticipate needs',
    'Personal touches, remembers orders, or friendly care',
    'Guests feel looked after without asking',
  ],
  authentic: [
    'Traditional techniques or flavors',
    'Tastes like the cuisine’s place of origin',
    'Mentions of cultural accuracy or heritage',
  ],
  creative_menu: [
    'Inventive dishes or unexpected combinations',
    'Chef-driven specials or seasonal twists',
    'Surprising presentations or flavors',
  ],
  comfort_food: [
    'Classic, hearty, or nostalgic dishes',
    'Stick-to-your-ribs portions',
    'Reminds guests of home cooking',
  ],
  healthy_options: [
    'Clean, light, or health-focused choices',
    'Vegetable-forward or low-calorie options',
    'Mentions of fresh, organic, or nutritious',
  ],
  portions_large: [
    'Huge portions or leftovers to take home',
    'Meals easily shared or split by guests',
    'Value praised because servings are big',
  ],
  vegan_friendly: [
    'Clearly labeled vegan dishes',
    'Multiple plant-based entrées',
    'Staff knowledgeable about vegan needs',
  ],
  photogenic_food: [
    'Beautiful plating or Instagram-worthy visuals',
    'Colorful dishes, latte art, or dramatic desserts',
    'Guests mention taking pictures',
  ],
  decor_quality: [
    'Thoughtful interior design or upscale finishes',
    'Stylish furniture, art, or statement pieces',
    'Atmosphere elevated by the surroundings',
  ],
  photo_friendly_lighting: [
    'Bright or natural light for clear photos',
    'Guests mention great lighting for content',
    'Space avoids dim or color-tinted lighting',
  ],
  nice_views: [
    'City skyline, waterfront, or scenic outlook',
    'Windows, rooftops, or patios with vistas',
    'Diners mention the view as a highlight',
  ],
  trendy: [
    'Hot spot with buzz or social media attention',
    'Crowd includes influencers or in-the-know locals',
    'Mentioned as fashionable or of-the-moment',
  ],
  outdoor_seating: [
    'Patio, sidewalk tables, or rooftop seating',
    'Comfortable alfresco setup',
    'Guests note enjoying fresh air or views outside',
  ],
  easy_parking: [
    'Own lot, valet, or abundant nearby parking',
    'Guests note parking as hassle-free',
    'Street parking usually available',
  ],
  reservations_needed: [
    'Bookings essential or walk-ins turned away',
    'Long waits without reservations',
    'Guests advise planning ahead',
  ],
  late_night: [
    'Kitchen open past 10–11pm',
    'Mentions of night owls or post-event dining',
    'Bar & food service late into the night',
  ],
  formality: [
    'Dress code, white tablecloth, or refined service',
    'Guests note formal etiquette or upscale feel',
    'Not a casual jeans-and-sneakers place',
  ],
  good_value: [
    'Portions, quality, and price feel fair',
    'Guests highlight bang-for-buck',
    'Affordable without sacrificing experience',
  ],
  splurge_worthy: [
    'Pricey but worth the spend',
    'Exceptional quality or experience justifies cost',
    'Guests recommend for special indulgence',
  ],
  popularity: [
    'Frequently mentioned, famous, or iconic',
    'Consistent crowds or buzz in reviews',
    'Recommended by many guests or locals',
  ],
};
